const fs = require("fs");
global.window = { addEventListener: function(){} };
global.document = { addEventListener: function(){}, getElementById: function(){ return { style:{}, classList:{toggle:function(){}}, textContent:"", innerHTML:"" }; }, querySelector: function(){ return { style:{}, classList:{}, textContent:"" }; }, querySelectorAll: function(){ return []; } };
global.localStorage = { getItem: function(){ return null; }, setItem: function(){}, removeItem: function(){} };
global.location = { hash: "#/home" };
global.confirm = function(){ return false; };
const base = "D:\\PROJECTS\\_AI\\AIBook_CyberPi\\AI编程探险课_CyberPi\\_parts";
let src = "";
["data1.js","data2.js","data3.js","data4.js"].forEach(f => src += fs.readFileSync(base + "\\" + f, "utf8") + "\n");
src += fs.readFileSync(base + "\\app.js", "utf8") + "\n";
src += 'console.log("JS OK, lessons:", ALL.length, "quiz:", ALL.reduce((n,l)=>n+l.quiz.length,0), "chapters:", CHAPTERS.length);';
eval(src);
